# file      : cxx/tree/custom/comments/buildfile
# license   : not copyrighted - public domain

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

./: exe{driver} doc{README}

exe{driver}: {hxx     cxx}{* -people -xml-schema} \
             {hxx ixx cxx}{people}                \
             {hxx        }{xml-schema}            \
             $libs

exe{driver}: xml{people}: test.input = true

<{hxx ixx cxx}{people}>: xsd{people} $xsd
{{
  $xsd cxx-tree                           \
       --generate-inline                  \
       --generate-serialization           \
       --extern-xml-schema xml-schema.xsd \
       --output-dir $out_base             \
       $path($<[0])
}}

hxx{xml-schema}: $xsd
{{
  diag xsd $>

  # Note that the specified xml-schema.xsd doesn't exist and is only used to
  # deduce the generated header name.
  #
  $xsd cxx-tree                                          \
       --generate-xml-schema                             \
       --generate-serialization                          \
       --custom-type anyType=/type_base                  \
       --hxx-epilogue '#include "xml-schema-custom.hxx"' \
       --output-dir $out_base                            \
       xml-schema.xsd
}}

cxx.poptions =+ "-I$out_base" "-I$src_base"

# Define XSD_CXX11 since we include libxsd headers directly.
#
cxx.poptions += -DXSD_CXX11
