# file      : cxx/tree/chameleon/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

exe{driver}: {hxx cxx}{* -includer} {hxx ixx cxx}{includer} $libs

exe{driver}: xml{test}:    test.input  = true
exe{driver}: file{output}: test.stdout = true

<{hxx ixx cxx}{includer}>: xsd{includer includee} $xsd
{{
  $xsd cxx-tree --std c++11     \
       --generate-inline      \
       --generate-ostream     \
       --root-element root    \
       --output-dir $out_base \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base"
