# file      : cxx/tree/build-in/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

exe{driver}: {hxx cxx}{* -types} {hxx ixx cxx}{types} $libs testscript

<{hxx ixx cxx}{types}>: xsd{types} $xsd
{{
  $xsd cxx-tree --std c++11      \
       --generate-inline         \
       --generate-ostream        \
       --generate-serialization  \
       --char-type char          \
       --generate-default-ctor   \
       --generate-from-base-ctor \
       --root-element-all        \
       --output-dir $out_base    \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base"
