# file      : cxx/parser/generated-impl/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

import libs = libxsd%lib{xsd}

exe{driver}: {hxx ixx cxx}{test-pskel}  \
             {hxx     cxx}{test-pimpl}  \
             {        cxx}{test-driver} \
             $libs

exe{driver}: xml{test}:    test.input  = true
exe{driver}: file{output}: test.stdout = true

cxx.poptions =+ "-I$out_base"

<{hxx ixx cxx}{test-pskel}                   \
 {hxx     cxx}{test-pimpl}                   \
 {        cxx}{test-driver}>: xsd{test} $xsd
{{
  diag xsd ($<[0]) # @@ TMP

  $xsd cxx-parser $xsd_cxx_std   \
       --generate-inline         \
       --skel-file-suffix -pskel \
       --generate-print-impl     \
       --generate-test-driver    \
       --force-overwrite         \
       --output-dir $out_base    \
       $path($<[0])
}}
