# file      : cxx/tree/prefix/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

fs = foo bar test

exe{driver}: {hxx cxx}{* -{$fs}} {hxx ixx cxx}{$fs} $libs

exe{driver}: xml{test}:    test.input  = true
exe{driver}: file{output}: test.stdout = true

for f: $fs
{
  <{hxx ixx cxx}{$f}>: xsd{$f} $xsd
  {{
    $xsd cxx-tree                      \
         --generate-inline             \
         --generate-serialization      \
         --generate-polymorphic        \
         --polymorphic-type 'foo#base' \
         --root-element root           \
         --output-dir $out_base        \
         $path($<[0])
  }}
}

cxx.poptions =+ "-I$out_base"
