# file      : schema/list/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

fs = test anonymous/test

./: {hxx cxx}{$fs}

# Make sure that the schema files are compilable.
#
for f: $fs
{
  <{hxx cxx}{$f}>: xsd{$f} $xsd
  {{
    diag xsd ($<[0]) # @@ TMP

    $xsd cxx-tree --std c++11                  \
         --root-element-all                    \
         --output-dir $directory($path($>[0])) \
         $path($<[0])
  }}
}

# Test that the invalid schema files compilation expectedly fails.
#
./: testscript xsd{** -{$fs}} $xsd

testscript{*}:
{
  test           = $xsd
  test.arguments = cxx-tree --std c++11
}
