# file      : libxsd/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

import int_libs  = libxerces-c%lib{xerces-c}
import int_libs += libexpat%lib{expat}

lib{xsd}: cxx/{hxx ixx txx}{** -version} cxx/{hxx}{version} $int_libs

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
cxx/
{
  hxx{version}: in{version} $src_root/manifest
  hxx{version}:
  {
    dist  = true
    clean = ($src_root != $out_root)
  }
}

# Export options.
#
lib{xsd}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs     = $int_libs
}

# Install into the libxsd/ subdirectory of, say, /usr/include/ recreating
# subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/libxsd/
  install.subdirs = true
}
