# file      : cxx/tree/polymorphism/comparison/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

exe{driver}: {hxx cxx}{* -test} {hxx ixx cxx}{test} $libs

exe{driver}: xml{test}: test.input = true

<{hxx ixx cxx}{test}>: xsd{test} $xsd
{{
  $xsd cxx-tree                 \
       --generate-inline        \
       --generate-serialization \
       --generate-polymorphic   \
       --polymorphic-type base  \
       --generate-comparison    \
       --output-dir $out_base   \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base"
