# file      : cxx/parser/validation/sequence/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

exe{driver}: {hxx cxx}{* -test-pskel} {hxx ixx cxx}{test-pskel} $libs \
             testscript

<{hxx ixx cxx}{test-pskel}>: xsd{test} $xsd
{{
  $xsd cxx-parser                \
       --generate-inline         \
       --skel-file-suffix -pskel \
       --output-dir $out_base    \
       --generate-validation     \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base"
