# file      : cxx/tree/binary/cdr/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}
import libs += libace%lib{ACE}

exe{driver}: {hxx cxx}{* -test} {hxx ixx cxx}{test} $libs

exe{driver}: xml{test}: test.input = true

<{hxx ixx cxx}{test}>: xsd{test} $xsd
{{
  $xsd cxx-tree --std c++11                 \
       --generate-inline                    \
       --generate-insertion 'ACE_OutputCDR' \
       --generate-extraction 'ACE_InputCDR' \
       --generate-comparison                \
       --output-dir $out_base               \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base"
