# file      : cxx/tree/caching/buildfile
# license   : not copyrighted - public domain

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

./: exe{driver} doc{README}

exe{driver}: {hxx cxx}{* -library} {hxx ixx cxx}{library} $libs

exe{driver}: {xml xsd}{library}: test.input = true

<{hxx ixx cxx}{library}>: xsd{library} $xsd
{{
  $xsd cxx-tree               \
       --generate-inline      \
       --output-dir $out_base \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base"

# Define XSD_CXX11 since we include libxsd headers directly.
#
cxx.poptions += -DXSD_CXX11
