# file      : cxx/parser/polyroot/buildfile
# license   : not copyrighted - public domain

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

./: exe{driver} doc{README} xml{batman person superman}

exe{driver}: {hxx cxx}{* -supermen-pskel} {hxx ixx cxx}{supermen-pskel} $libs \
             testscript

<{hxx ixx cxx}{supermen-pskel}>: xsd{supermen} $xsd
{{
  $xsd cxx-parser                \
       --generate-inline         \
       --skel-file-suffix -pskel \
       --generate-polymorphic    \
       --output-dir $out_base    \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base" "-I$src_base"
