# file      : schema/any/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

# Just make sure that the schema files and the xsd-generated C++ mappings are
# compilable.
#
import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

for sc: test fail
{
  dr = "driver-$sc"

  ./: exe{$dr}: cxx{$dr} {hxx cxx}{$sc} $libs

  cxx{$dr}: in{driver}
  {
    # Note: we can't use $sc$ in driver.cxx.in since it will be substituted by
    # the latest $sc value.
    #
    sch = $sc
  }
}

<{hxx cxx}{test}>: xsd{test} $xsd
{{
  diag xsd ($<[0]) # @@ TMP

  $xsd cxx-tree --std c++11   \
       --root-element-all     \
       --output-dir $out_base \
       $path($<[0])
}}

<{hxx cxx}{fail}>: xsd{fail} $xsd
{{
  diag xsd ($<[0]) # @@ TMP

  $xsd cxx-tree --std c++11   \
       --root-element-all     \
       --output-dir $out_base \
       $path($<[0]) 2>>?~%EOE%
    %.+(warning T001:|info:).+%{9}
    EOE
}}

cxx.poptions =+ "-I$out_base"
