# file      : cxx/tree/compression/buildfile
# license   : not copyrighted - public domain

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}
import libs += libz%lib{z}

./: exe{driver} file{library.xml.gz} doc{README}

exe{driver}: {hxx cxx}{* -library} {hxx ixx cxx}{library} $libs testscript

<{hxx ixx cxx}{library}>: xsd{library} $xsd
{{
  $xsd cxx-tree                 \
       --generate-inline        \
       --generate-serialization \
       --generate-ostream       \
       --output-dir $out_base   \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base" "-I$src_base"

# Define XSD_CXX11 since we include libxsd headers directly.
#
cxx.poptions += -DXSD_CXX11
