# file      : schema/inheritance/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

fs = cycle sourced-forward/includer

./: {hxx cxx}{$fs}

# Make sure that the schema files are compilable.
#
for f: $fs
{
  <{hxx cxx}{$f}>: xsd{$f} $xsd
  {{
    $xsd cxx-tree                              \
         --output-dir $directory($path($>[0])) \
         $path($<[0])
  }}
}

# Test that the invalid schema files compilation expectedly fails.
#
./: testscript xsd{** -{$fs}} $xsd

testscript{*}:
{
  test           = $xsd
  test.arguments = cxx-tree
}
