# file      : cxx/parser/hello/buildfile
# license   : not copyrighted - public domain

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

./: exe{driver} doc{README}

exe{driver}: {hxx cxx}{* -hello-pskel} {hxx ixx cxx}{hello-pskel} $libs

exe{driver}: xml{hello}: test.input = true

<{hxx ixx cxx}{hello-pskel}>: xsd{hello} $xsd
{{
  $xsd cxx-parser                \
       --generate-inline         \
       --skel-file-suffix -pskel \
       --output-dir $out_base    \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base"
