# file      : processing/inheritance/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

# Just make sure that the schema files and the xsd-generated C++ mappings are
# compilable.
#
import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

for nm: 000 001
{
  dr = "driver-$nm"
  sc = "test-$nm"

  ./: exe{$dr}: cxx{$dr} {hxx cxx}{$sc} $libs

  cxx{$dr}: in{driver}
  {
    # Note: we can't use $nm$ in driver.cxx.in since it will be substituted by
    # the latest $nm value.
    #
    num = $nm
  }

  <{hxx cxx}{$sc}>: xsd{$sc} $xsd
  {{
    diag xsd ($<[0]) # @@ TMP

    $xsd cxx-tree --std c++11   \
         --root-element-all     \
         --output-dir $out_base \
         $path($<[0])
  }}
}

cxx.poptions =+ "-I$out_base"
