# file      : cxx/tree/binary/xdr-ordered/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

if ($cxx.target.class == 'linux')
  import libs += libtirpc%lib{tirpc}

exe{driver}: {hxx cxx}{* -test} {hxx ixx cxx}{test} $libs

exe{driver}: xml{test}: test.input = true

<{hxx ixx cxx}{test}>: xsd{test} $xsd
{{
  $xsd cxx-tree --std c++11        \
       --generate-inline           \
       --generate-insertion 'XDR'  \
       --generate-extraction 'XDR' \
       --generate-comparison       \
       --ordered-type-all          \
       --output-dir $out_base      \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base"
