# file      : cxx/tree/order/mixed/buildfile
# license   : not copyrighted - public domain

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

./: exe{driver} doc{README}

exe{driver}: {hxx cxx}{* -text} {hxx ixx cxx}{text} $libs

exe{driver}: xml{text}: test.input = true

<{hxx ixx cxx}{text}>: xsd{text} $xsd
{{
  $xsd cxx-tree                 \
       --generate-inline        \
       --generate-serialization \
       --ordered-type-mixed     \
       --output-dir $out_base   \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base"
