# file      : morphing/anonymous/attribute-group/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

exe{driver}: {hxx cxx}{* -test} {hxx cxx}{test} $libs

cxx.poptions =+ "-I$out_base"

<{hxx cxx}{test}>: xsd{test} $xsd
{{
  diag xsd ($<[0]) # @@ TMP

  $xsd cxx-tree $xsd_cxx_std  \
       --root-element-all     \
       --output-dir $out_base \
       $path($<[0])
}}
