# file      : cxx/tree/mixed/buildfile
# license   : not copyrighted - public domain

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

./: exe{driver} doc{README}

exe{driver}: {hxx cxx}{* -text} {hxx ixx cxx}{text} $libs

exe{driver}: xml{text}: test.input = true

<{hxx ixx cxx}{text}>: xsd{text} $xsd
{{
  $xsd cxx-tree --std c++11   \
       --generate-inline      \
       --output-dir $out_base \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base"

# Define XSD_CXX11 since we include libxsd headers directly.
#
cxx.poptions += -DXSD_CXX11
