# file      : cxx/parser/enumeration/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

import libs = libxsd%lib{xsd}

exe{driver}: {hxx cxx}{* -test-pskel} {hxx ixx cxx}{test-pskel} $libs

exe{driver}: xml{test}:    test.input  = true
exe{driver}: file{output}: test.stdout = true

cxx.poptions =+ "-I$out_base" "-I$src_base"

<{hxx ixx cxx}{test-pskel}>: xsd{test} map{test} $xsd
{{
  diag xsd ($<[0]) # @@ TMP

  $xsd cxx-parser $xsd_cxx_std   \
       --generate-inline         \
       --skel-file-suffix -pskel \
       --output-dir $out_base    \
       --type-map $path($<[1])   \
       $path($<[0])
}}
