# file      : cxx/tree/messaging/buildfile
# license   : not copyrighted - public domain

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

./: exe{driver} xml{balance deposit withdraw} doc{README}

exe{driver}: {hxx cxx}{* -protocol} {hxx ixx cxx}{protocol} $libs testscript

<{hxx ixx cxx}{protocol}>: xsd{protocol} $xsd
{{
  $xsd cxx-tree                 \
       --generate-inline        \
       --root-element-all       \
       --generate-element-type  \
       --generate-element-map   \
       --generate-serialization \
       --output-dir $out_base   \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base" "-I$src_base"

# Define XSD_CXX11 since we include libxsd headers directly.
#
cxx.poptions += -DXSD_CXX11
