# file      : schema/ref-type/valid/buildfile
# license   : GNU GPL v2 + exceptions; see accompanying LICENSE file

# Just make sure that the schema files and the xsd-generated C++ mappings are
# compilable.
#
import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

for sc: idref idrefs
{
  dr = "driver-$sc"

  ./: exe{$dr}: cxx{$dr} {hxx cxx}{$sc} $libs

  cxx{$dr}: in{driver}
  {
    # Note: we can't use $sc$ in driver.cxx.in since it will be substituted by
    # the latest $sc value.
    #
    sch = $sc
  }

  <{hxx cxx}{$sc}>: xsd{$sc} $xsd
  {{
    $xsd cxx-tree               \
         --root-element-all     \
         --output-dir $out_base \
         $path($<[0])
  }}
}

cxx.poptions =+ "-I$out_base"
