# file      : cxx/tree/binary/boost/buildfile
# license   : not copyrighted - public domain

import libs  = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}
import libs += libboost-serialization%lib{boost_serialization}

./: exe{driver} doc{README}

exe{driver}: {hxx cxx}{* -library} {hxx ixx cxx}{library} $libs

exe{driver}: xml{library}: test.input = true

<{hxx ixx cxx}{library}>: xsd{library} hxx{library-prologue} $xsd
{{
  diag xsd ($<[0]) # @@ TMP

  $xsd cxx-tree --std c++11                                  \
       --generate-inline                                     \
       --generate-ostream                                    \
       --hxx-prologue-file $path($<[1])                      \
       --generate-insertion  'boost::archive::text_oarchive' \
       --generate-extraction 'boost::archive::text_iarchive' \
       --output-dir $out_base                                \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base" "-I$src_base"

# Define XSD_CXX11 since we include libxsd headers directly.
#
cxx.poptions += -DXSD_CXX11
