# file      : cxx/tree/streaming/buildfile
# license   : not copyrighted - public domain

import libs = libxsd%lib{xsd}
import libs += libxerces-c%lib{xerces-c}

./: exe{driver} xml{position} doc{README}

exe{driver}: {hxx cxx}{* -position} {hxx ixx cxx}{position} $libs testscript

<{hxx ixx cxx}{position}>: xsd{position} $xsd
{{
  $xsd cxx-tree                 \
       --generate-inline        \
       --generate-serialization \
       --output-dir $out_base   \
       $path($<[0])
}}

cxx.poptions =+ "-I$out_base" "-I$src_base"

# Define XSD_CXX11 since we include libxsd headers directly.
#
cxx.poptions += -DXSD_CXX11
